### ISSUE TITLE
pika.exceptions.AMQPConnectionError

### ISSUE THREAD

**Issue by Flamtky** [SmartCity-2022/Service-Bauamt#11]
INFO: Started server process [1]
INFO: Waiting for application startup.
Exception in thread Thread-1 (run):
Traceback (most recent call last):
File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.10/threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
ERROR: Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 621, in lifespan
async with self.lifespan_context(app):
File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 518, in __aenter__
await self._router.startup()
File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 598, in startup
await handler()
File "/code/./main.py", line 18, in startup
send(key=configParser.get("rabbitMQ-routes", "HELLO"), payload="test")
File "/code/./src/util/sender.py", line 11, in send
connection = pika.BlockingConnection(pika.ConnectionParameters(
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
self._impl = self._create_connection(parameters, _impl_class)
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
ERROR: Application startup failed. Exiting.
return future.result()
File "/code/./main.py", line 24, in test
receiver.run()
File "/code/./src/util/receiver.py", line 17, in run
connection = pika.BlockingConnection(pika.ConnectionParameters(
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
self._impl = self._create_connection(parameters, _impl_class)
File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError

**Comment by mjleenders** [comment]
Ich kriege dieselbe Fehlernachricht bei mir wenn ich Docker nicht laufen hab und mein Programm keine Verbindung aufbauen kann. Also sollte das klappen wenn die richtigen Daten in der Config stehen.

**Comment by Flamtky** [comment]
> Ich kriege dieselbe Fehlernachricht bei mir wenn ich Docker nicht laufen hab und mein Programm keine Verbindung aufbauen kann. Also sollte das klappen wenn die richtigen Daten in der Config stehen.

Okay, lag an der gegeben Config
